name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: |
          docker buildx build \
            --build-arg REACT_APP_NODE_ENV='production' \
            --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}' \
            --file Dockerfile \
            -t johin12/chefdelightsfrontend \
            --push .
      - name: Publish Image to Docker Hub
        run: docker push johin12/chefdelightsfrontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull johin12/chefdelightsfrontend:latest
      - name: Delete old container
        run: docker rm -f reactjs-app-container || true
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container johin12/chefdelightsfrontend
